# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f7a5c461d3e3ab8b3d136adef32f51c8fb4c5d60f5610593a2e05bf5f4f77928b7f27d3e0d5fd1858bc5df2713d02941cbe18b2df4223512560ee032ce34dc75

test:
  secret_key_base: 0b7a20c47e78c52512deae15587e31fd49170d0c44ea5480d288dc2c7035dc6e1f22fd957fb633ee290e09fe2e77e43734dd46d926147be45167c6f2c807d560

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
